name: 'get-package-version-id'
description: 'Gets package version id'
author: '808Brinks'
inputs:
  packageOwner: # change this
    required: true
    description: 'Owner of the package'
  packageName: # change this
    required: true
    description: 'Name of the package'
  packageType: # change this
    required: true
    description: 'Type of the package (npm)'
    default: 'npm'
  packageVersionName: # change this
    required: true
    description: 'Name version of the package'
  githubToken:
    required: true
    description: 'Github token'
outputs:
  packageVersionId:
    description: 'The package version id'
runs:
  using: 'node16'
  main: 'dist/index.js'
